---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iplas.
--- DateTime: 2018/11/5 11:47
---

local json = require('cjson')
local result = {}
local count = 0
local len = redis.call('ZCARD', redisKey)
local rows = redis.call('ZREVRANGE', redisKey, 0, len)
local result_index = 1
local start = tonumber(ARGV[2])
local limit = tonumber(ARGV[3])

for _, value in pairs(rows) do
    local replacedString, _ = string.gsub(value, "^%[CQ:image.term=2%]$", "")
    local _, enpos = string.find(replacedString, primaryKey)
    if nil ~= enpos then
        count = count + 1
        if start < count and count <= (limit + start) then
            result[result_index] = json.decode(value)
            result_index = result_index + 1
        end
    end
end
return {result, count}