---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iplas.
--- DateTime: 2018/10/31 10:44
---

function case_insensitive_pattern(pattern)

    -- find an optional '%' (group 1) followed by any character (group 2)
    local p = pattern:gsub("(%%?)(.)", function(percent, letter)

        if percent ~= "" or not letter:match("%a") then
            -- if the '%' matched, or `letter` is not a letter, return "as is"
            return percent .. letter
        else
            -- else, return a case-insensitive character class of the matched letter
            return string.format("[%s%s]", letter:lower(), letter:upper())
        end

    end)

    return p
end

print(case_insensitive_pattern("xyz = %d+ or %% end"))