---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iplas.
--- DateTime: 2018/10/31 11:57
---

function case_insensitive_pattern(pattern)
    -- find an optional '%' (group 1) followed by any character (group 2)
    local p = pattern:gsub("(%%?)(.)", function(percent, letter)
        if percent ~= "" or not letter:match("%a") then
            -- if the '%' matched, or `letter` is not a letter, return "as is"
            return percent .. letter
        else
            -- else, return a case-insensitive character class of the matched letter
            return string.format("[%s%s]", letter:lower(), letter:upper())
        end
    end)
    return p
end

local function deserialization_to_object(sourceString)
    --    删除"staffName"干扰
    object = sourceString .. "===="
    return object
end
local value = nil
value = string.find("asdasdasd", "a")
--print(temp)
print(value)
print(string.find("asdasdasd", "%[CQ:image.-%]"))

local tempString = "90"
local selectType = "2"
local enpos = nil
if (selectType == "1") then
    -- 修改去除图片url的影响
    local replacedString, _ = string.gsub(value, "%[CQ:image.-%]", "")
elseif (selectType == "2") then
    -- 直接筛选图片的数据
    enpos = string.find(tempString, "%[CQ:image.-%]")
end
print(enpos)